### ISSUE TITLE
Background not appearing

### ISSUE THREAD

**Issue by RosesMikr** [Bylander10/Niko-Theme-for-Discord#1]
I dont really know if i have to install other things or anything similar, but whenever i try to use the theme on vencord, everything works except the background. appearing pitch black instead of the niko image

**Comment by Bylander10** [comment]
It may be a gif domain problem, I'll upload the gif to a more stable database

**Comment by Bylander10** [comment]
Uploaded the gif background to imgbb, it might work normally now
